### PR TITLE
installed prettier, added .prettierrc and .prettierignore

### LINKED ISSUE #14: Implement an auto-formatter
in order to have a functional workflow an auto-formatter is needed. We want to avoid being extension-dependant, so every developer is able to jump in and use the same formatting rules without the need of an extension

- [x] choose prettier or pretty
- [x] install and configurate

### PR DESCRIPTION
**Pull request by AlbertLeipzig**

### CODE REVIEW

**Comment by AlbertLeipzig** [comment]
I installed [prettier](https://prettier.io/)

Added the script "prettier", which will format "every" (keep reading ;)) file. It runs with the default configuration. Although I very much like it, it still can be altered.

- .prettierrc is the config file, where we can change the default config. The options are [here](https://prettier.io/docs/en/options). You can change it yourself, or send me a request, and I'll take care of it
 
- in order not to format every file, a .prettierignore was added, so build and test files are not unnecessary formatted. More about that in [here](https://prettier.io/docs/en/ignore)

- I'd suggest to run prettier in paralel with start (so it formats regularly "by it's own") or add a "commit-script", so it formats **before** commiting

**Review by tkalejandro — CHANGES_REQUESTED** [review]
I see that prettier chang everything to double quote "" , can we config to be actual  single quote'' ?? thank you :-)

Just to confirm, when we save the code, prettier do the owrk right? @AlbertLeipzig

**Comment by tkalejandro** [comment]
I will fix Prettier in another PR. @AlbertLeipzig because I want to upgrade to a different version of next, so lets see.

**Review by tkalejandro — APPROVED** [review]
Approve. Please create another ticket for Prettier Rules

**Pull request merged**
